sudo: false
rvm:
  - 2.2.6
  - 2.3.1
  - ruby-head
  - rbx-2
gemfile:
  - Gemfile
  # - gemfiles/Gemfile.representable-2.4
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
