language: ruby
sudo: false
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 1.9.3
    - rvm: 2.1
    - rvm: 2.2.6
    - rvm: 2.3.1
    - rvm: 2.4.0
    - rvm: jruby-9.1.13.0
    - rvm: ruby-head
